### ISSUE TITLE
lastLocationUpdatedAt not updated

### ISSUE THREAD

**Issue by alexsup** [Supmenow/sup-ios-issues#143] opened 2016-07-18 11:47 UTC
We are not certain that lastLocationUpdatedAt is being updated.

** Moved

**Comment by jcampbell05** [comment] 2016-07-20 10:41
We should look into if the user's effected are people who upgraded, is there anything common between them ?

**Comment by jcampbell05** [comment] 2016-07-20 11:08
Duplicate of https://github.com/Supmenow/Sup-iOS/issues/1269

**Closed by jcampbell05** 2016-07-20 11:08 UTC
Labels: waiting input
